server:
  port: 8085
vaadin:
  compatibilityMode : false
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/pastelitos
    username: postgres
    password: admin-pg12
    initialization-mode: always
    initialize: true
    #schema: classpath:/schema.sql
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    # = org.hibernate.dialect.PostgreSQLDialect
